import type { Card, CreatureCard, FormationCard, SpellCard } from './types'

export const CREATURE_CARDS = [
  {
    definitionId: 'red-cost2-attack3-defense2-march1',
    name: '火花の剣兵',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 3,
    defense: 2,
    march: 1,
    abilities: [],
  },
  {
    definitionId: 'blue-cost2-attack2-defense2-march2',
    name: '潮路の斥候',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 2,
    defense: 2,
    march: 2,
    abilities: [],
  },
  {
    definitionId: 'green-cost2-attack2-defense3-march1',
    name: '樫皮の番兵',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 2,
    defense: 3,
    march: 1,
    abilities: [],
  },
  {
    definitionId: 'red-cost2-attack4-defense1-march1',
    name: '燃え立つ先陣',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 4,
    defense: 1,
    march: 1,
    abilities: [],
  },
  {
    definitionId: 'blue-cost2-attack2-defense1-march3',
    name: '飛沫の伝令',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 2,
    defense: 1,
    march: 3,
    abilities: [],
  },
  {
    definitionId: 'green-cost2-attack2-defense4-march0',
    name: '根張りの古木',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 2,
    defense: 4,
    march: 0,
    abilities: [],
  },
  {
    definitionId: 'red-cost4-attack5-defense2-march2',
    name: '烽火の重騎兵',
    kind: 'creature',
    color: 'red',
    cost: 4,
    attack: 5,
    defense: 2,
    march: 2,
    abilities: [],
  },
  {
    definitionId: 'blue-cost4-attack4-defense4-march3',
    name: '蒼波の航海士',
    kind: 'creature',
    color: 'blue',
    cost: 4,
    attack: 4,
    defense: 4,
    march: 3,
    abilities: [],
  },
  {
    definitionId: 'green-cost4-attack4-defense6-march2',
    name: '巨樹の守護者',
    kind: 'creature',
    color: 'green',
    cost: 4,
    attack: 4,
    defense: 6,
    march: 2,
    abilities: [],
  },
  {
    definitionId: 'red-cost5-attack7-defense4-march2-vanish',
    name: '燃え尽きる火山竜',
    kind: 'creature',
    color: 'red',
    cost: 5,
    attack: 7,
    defense: 4,
    march: 2,
    abilities: [{ type: 'vanish' }],
  },
  {
    definitionId: 'blue-cost5-attack5-defense6-march4-vanish',
    name: '泡沫の深海鯨',
    kind: 'creature',
    color: 'blue',
    cost: 5,
    attack: 5,
    defense: 6,
    march: 4,
    abilities: [{ type: 'vanish' }],
  },
  {
    definitionId: 'green-cost5-attack6-defense7-march2-vanish',
    name: '夢渡りの森巨人',
    kind: 'creature',
    color: 'green',
    cost: 5,
    attack: 6,
    defense: 7,
    march: 2,
    abilities: [{ type: 'vanish' }],
  },
  {
    definitionId: 'red-cost2-attack2-defense1-march1-lone-warrior-2-0',
    name: '孤峰の剣士',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 2,
    defense: 1,
    march: 1,
    abilities: [{ type: 'loneWarrior', attack: 2, defense: 0 }],
  },
  {
    definitionId: 'red-cost2-attack3-defense1-march1-withdraw',
    name: '陣払いの傭兵',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 3,
    defense: 1,
    march: 1,
    abilities: [{ type: 'withdraw' }],
  },
  {
    definitionId: 'red-cost2-attack2-defense1-march1-assassin2',
    name: '朱刃の潜入者',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 2,
    defense: 1,
    march: 1,
    abilities: [{ type: 'assassin', attack: 2 }],
  },
  {
    definitionId: 'blue-cost2-attack3-defense1-march1-counter',
    name: '逆巻く決闘士',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 3,
    defense: 1,
    march: 1,
    abilities: [{ type: 'counter' }],
  },
  {
    definitionId: 'blue-cost2-attack2-defense1-march2-return',
    name: '霧渡りの使者',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 2,
    defense: 1,
    march: 2,
    abilities: [{ type: 'return' }],
  },
  {
    definitionId: 'blue-cost2-attack2-defense2-march1-beachhead1',
    name: '潮先の築城師',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 2,
    defense: 2,
    march: 1,
    abilities: [{ type: 'beachhead', costReduction: 1 }],
  },
  {
    definitionId: 'green-cost2-attack2-defense3-march0-capture1',
    name: '蔦罠の狩人',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 2,
    defense: 3,
    march: 0,
    abilities: [{ type: 'capture', marchTax: 1 }],
  },
  {
    definitionId: 'green-cost2-attack2-defense2-march1-mining1',
    name: '晶洞の坑夫',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 2,
    defense: 2,
    march: 1,
    abilities: [{ type: 'mining', mana: 1 }],
  },
  {
    definitionId: 'green-cost2-attack2-defense2-march1-rearguard-0-2',
    name: '根砦の殿軍',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 2,
    defense: 2,
    march: 1,
    abilities: [{ type: 'rearguard', attack: 0, defense: 2 }],
  },
  {
    definitionId: 'red-cost4-attack4-defense2-march2-lone-warrior-2-1',
    name: '孤軍の猛将',
    kind: 'creature',
    color: 'red',
    cost: 4,
    attack: 4,
    defense: 2,
    march: 2,
    abilities: [{ type: 'loneWarrior', attack: 2, defense: 1 }],
  },
  {
    definitionId: 'red-cost4-attack5-defense1-march2-withdraw',
    name: '灰燼の解体者',
    kind: 'creature',
    color: 'red',
    cost: 4,
    attack: 5,
    defense: 1,
    march: 2,
    abilities: [{ type: 'withdraw' }],
  },
  {
    definitionId: 'blue-cost4-attack3-defense4-march2-counter',
    name: '深潮の迎撃者',
    kind: 'creature',
    color: 'blue',
    cost: 4,
    attack: 3,
    defense: 4,
    march: 2,
    abilities: [{ type: 'counter' }],
  },
  {
    definitionId: 'blue-cost4-attack4-defense2-march2-return',
    name: '波間の帰還術師',
    kind: 'creature',
    color: 'blue',
    cost: 4,
    attack: 4,
    defense: 2,
    march: 2,
    abilities: [{ type: 'return' }],
  },
  {
    definitionId: 'green-cost4-attack4-defense5-march1-capture2',
    name: '森檻の獣使い',
    kind: 'creature',
    color: 'green',
    cost: 4,
    attack: 4,
    defense: 5,
    march: 1,
    abilities: [{ type: 'capture', marchTax: 2 }],
  },
  {
    definitionId: 'green-cost4-attack4-defense4-march2-mining1',
    name: '地脈掘りの巨人',
    kind: 'creature',
    color: 'green',
    cost: 4,
    attack: 4,
    defense: 4,
    march: 2,
    abilities: [{ type: 'mining', mana: 1 }],
  },
] satisfies CreatureCard[]

export const FORMATION_CARDS = [
  {
    definitionId: 'red-cost3-formation',
    name: '孤軍を照らす烽火',
    kind: 'formation',
    color: 'red',
    cost: 3,
    text: '自分の赤クリーチャーを含むグループが2つ以上ある間、グループが1体の自分のすべての赤クリーチャーは一騎当千(+1/+0)を持つ。',
  },
  {
    definitionId: 'blue-cost3-formation',
    name: '逆潮の戦列',
    kind: 'formation',
    color: 'blue',
    cost: 3,
    text: '自分の青クリーチャーを含むグループが2つ以上ある間、グループが1体の自分のすべての青クリーチャーは反撃を持つ。既に反撃を持っている場合攻撃力+1する。',
  },
  {
    definitionId: 'green-cost3-formation',
    name: '千樹の連環',
    kind: 'formation',
    color: 'green',
    cost: 3,
    text: '自分の緑クリーチャーを含むグループが2つ以上ある間、1体だけでグループを作っている自分の緑クリーチャーは防御力+1。自分の緑クリーチャーを含むグループが3つ以上ある場合、自分のキープアップフェイズに追加で1マナを得る。',
  },
] satisfies FormationCard[]

export const SPELL_CARDS = [] satisfies SpellCard[]

export const CARD_LIST = [
  ...CREATURE_CARDS,
  ...FORMATION_CARDS,
  ...SPELL_CARDS,
] satisfies Card[]

export const CARD_BY_DEFINITION_ID = Object.fromEntries(
  CARD_LIST.map((card) => [card.definitionId, card]),
) as Record<string, Card>
