import type { Card, CreatureCard, FormationCard, SpellCard } from './types'

export const CREATURE_CARDS = [
  {
    definitionId: 'red-cost2-attack3-defense2-march1',
    name: '赤 コスト2 攻3 防2 進1',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 3,
    defense: 2,
    march: 1,
    abilities: [],
  },
  {
    definitionId: 'blue-cost2-attack1-defense2-march2',
    name: '青 コスト2 攻1 防2 進2',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 1,
    defense: 2,
    march: 2,
    abilities: [],
  },
  {
    definitionId: 'green-cost2-attack2-defense3-march1',
    name: '緑 コスト2 攻2 防3 進1',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 2,
    defense: 3,
    march: 1,
    abilities: [],
  },
  {
    definitionId: 'red-cost2-attack4-defense1-march1',
    name: '赤 コスト2 攻4 防1 進1',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 4,
    defense: 1,
    march: 1,
    abilities: [],
  },
  {
    definitionId: 'blue-cost2-attack0-defense1-march3',
    name: '青 コスト2 攻0 防1 進3',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 0,
    defense: 1,
    march: 3,
    abilities: [],
  },
  {
    definitionId: 'green-cost2-attack1-defense4-march1',
    name: '緑 コスト2 攻1 防4 進1',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 1,
    defense: 4,
    march: 1,
    abilities: [],
  },
  {
    definitionId: 'red-cost4-attack6-defense4-march2',
    name: '赤 コスト4 攻6 防4 進2',
    kind: 'creature',
    color: 'red',
    cost: 4,
    attack: 6,
    defense: 4,
    march: 2,
    abilities: [],
  },
  {
    definitionId: 'blue-cost4-attack2-defense4-march3',
    name: '青 コスト4 攻2 防4 進3',
    kind: 'creature',
    color: 'blue',
    cost: 4,
    attack: 2,
    defense: 4,
    march: 3,
    abilities: [],
  },
  {
    definitionId: 'green-cost4-attack4-defense6-march1',
    name: '緑 コスト4 攻4 防6 進1',
    kind: 'creature',
    color: 'green',
    cost: 4,
    attack: 4,
    defense: 6,
    march: 1,
    abilities: [],
  },
  {
    definitionId: 'red-cost5-attack8-defense6-march3-vanish',
    name: '赤 コスト5 攻8 防6 進3 消滅',
    kind: 'creature',
    color: 'red',
    cost: 5,
    attack: 8,
    defense: 6,
    march: 3,
    abilities: ['消滅'],
  },
  {
    definitionId: 'blue-cost5-attack4-defense6-march4-vanish',
    name: '青 コスト5 攻4 防6 進4 消滅',
    kind: 'creature',
    color: 'blue',
    cost: 5,
    attack: 4,
    defense: 6,
    march: 4,
    abilities: ['消滅'],
  },
  {
    definitionId: 'green-cost5-attack6-defense8-march3-vanish',
    name: '緑 コスト5 攻6 防8 進3 消滅',
    kind: 'creature',
    color: 'green',
    cost: 5,
    attack: 6,
    defense: 8,
    march: 3,
    abilities: ['消滅'],
  },
  {
    definitionId: 'red-cost2-attack2-defense2-march1-lone-warrior-2-0',
    name: '赤 コスト2 一騎当千',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 2,
    defense: 2,
    march: 1,
    abilities: ['一騎当千(+2/+0)'],
  },
  {
    definitionId: 'red-cost2-attack3-defense1-march1-withdraw',
    name: '赤 コスト2 撤去',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 3,
    defense: 1,
    march: 1,
    abilities: ['撤去'],
  },
  {
    definitionId: 'red-cost2-attack2-defense2-march1-assassin2',
    name: '赤 コスト2 刺客2',
    kind: 'creature',
    color: 'red',
    cost: 2,
    attack: 2,
    defense: 2,
    march: 1,
    abilities: ['刺客2'],
  },
  {
    definitionId: 'blue-cost2-attack3-defense1-march1-counter',
    name: '青 コスト2 反撃',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 3,
    defense: 1,
    march: 1,
    abilities: ['反撃'],
  },
  {
    definitionId: 'blue-cost2-attack1-defense1-march2-return',
    name: '青 コスト2 帰還',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 1,
    defense: 1,
    march: 2,
    abilities: ['帰還'],
  },
  {
    definitionId: 'blue-cost2-attack2-defense2-march1-beachhead1',
    name: '青 コスト2 橋頭堡1',
    kind: 'creature',
    color: 'blue',
    cost: 2,
    attack: 2,
    defense: 2,
    march: 1,
    abilities: ['橋頭堡1'],
  },
  {
    definitionId: 'green-cost2-attack1-defense3-march1-capture1',
    name: '緑 コスト2 捕獲1',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 1,
    defense: 3,
    march: 1,
    abilities: ['捕獲1'],
  },
  {
    definitionId: 'green-cost2-attack2-defense2-march1-mining1',
    name: '緑 コスト2 採掘1',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 2,
    defense: 2,
    march: 1,
    abilities: ['採掘1'],
  },
  {
    definitionId: 'green-cost2-attack2-defense2-march1-rearguard-0-2',
    name: '緑 コスト2 しんがり',
    kind: 'creature',
    color: 'green',
    cost: 2,
    attack: 2,
    defense: 2,
    march: 1,
    abilities: ['しんがり(+0/+2)'],
  },
  {
    definitionId: 'red-cost4-attack5-defense3-march2-lone-warrior-2-1',
    name: '赤 コスト4 一騎当千',
    kind: 'creature',
    color: 'red',
    cost: 4,
    attack: 5,
    defense: 3,
    march: 2,
    abilities: ['一騎当千(+2/+1)'],
  },
  {
    definitionId: 'red-cost4-attack5-defense3-march2-withdraw',
    name: '赤 コスト4 撤去',
    kind: 'creature',
    color: 'red',
    cost: 4,
    attack: 5,
    defense: 3,
    march: 2,
    abilities: ['撤去'],
  },
  {
    definitionId: 'blue-cost4-attack3-defense4-march2-counter',
    name: '青 コスト4 反撃',
    kind: 'creature',
    color: 'blue',
    cost: 4,
    attack: 3,
    defense: 4,
    march: 2,
    abilities: ['反撃'],
  },
  {
    definitionId: 'blue-cost4-attack4-defense2-march2-return',
    name: '青 コスト4 帰還',
    kind: 'creature',
    color: 'blue',
    cost: 4,
    attack: 4,
    defense: 2,
    march: 2,
    abilities: ['帰還'],
  },
  {
    definitionId: 'green-cost4-attack2-defense5-march2-capture1',
    name: '緑 コスト4 捕獲1',
    kind: 'creature',
    color: 'green',
    cost: 4,
    attack: 2,
    defense: 5,
    march: 2,
    abilities: ['捕獲1'],
  },
  {
    definitionId: 'green-cost4-attack3-defense4-march2-mining1',
    name: '緑 コスト4 採掘1',
    kind: 'creature',
    color: 'green',
    cost: 4,
    attack: 3,
    defense: 4,
    march: 2,
    abilities: ['採掘1'],
  },
] satisfies CreatureCard[]

export const FORMATION_CARDS = [
  {
    definitionId: 'red-cost4-formation',
    name: '赤の布陣',
    kind: 'formation',
    color: 'red',
    cost: 4,
    text: '自分の赤クリーチャーを含むグループが2つ以上ある間、グループが1体の自分のすべての赤クリーチャーは一騎当千(+1/+1)を持つ。',
  },
  {
    definitionId: 'blue-cost4-formation',
    name: '青の布陣',
    kind: 'formation',
    color: 'blue',
    cost: 4,
    text: '自分の青クリーチャーを含むグループが2つ以上ある間、グループが1体の自分のすべての青クリーチャーは反撃を持つ。既に反撃を持っている場合攻撃力+1する。',
  },
  {
    definitionId: 'green-cost4-formation',
    name: '緑の布陣',
    kind: 'formation',
    color: 'green',
    cost: 4,
    text: '自分の緑クリーチャーを含むグループが2つ以上ある間、1体だけでグループを作っている自分の緑クリーチャーは防御力+1。自分の緑クリーチャーを含むグループが3つ以上ある場合、自分のキープアップフェイズに追加で1マナを得る。',
  },
] satisfies FormationCard[]

export const SPELL_CARDS = [] satisfies SpellCard[]

export const CARD_LIST = [
  ...CREATURE_CARDS,
  ...FORMATION_CARDS,
  ...SPELL_CARDS,
] satisfies Card[]

export const CARD_BY_DEFINITION_ID = Object.fromEntries(
  CARD_LIST.map((card) => [card.definitionId, card]),
) as Record<string, Card>
