import { CARD_DEFINITION_IDS } from './cards'
import type { CardColor, CardDefinitionId } from './types'

const CARD_ID = CARD_DEFINITION_IDS

export const THEME_DECK_IDS = [
  'red-blue-skirmish',
  'blue-green-intercept',
  'green-red-frontline',
] as const

export type ThemeDeckId = (typeof THEME_DECK_IDS)[number]

export type ThemeDeck = {
  id: ThemeDeckId
  name: string
  colors: [CardColor, CardColor]
  description: string
  cardDefinitionIds: readonly CardDefinitionId[]
}

// Source order is stable because fixed-seed tournament shuffling starts from this order.
const RED_BLUE_SKIRMISH = [
  CARD_ID.SPARK_SWORDSMAN,
  CARD_ID.SPARK_SWORDSMAN,
  CARD_ID.SPARK_SWORDSMAN,
  CARD_ID.BURNING_VANGUARD,
  CARD_ID.BURNING_VANGUARD,
  CARD_ID.BURNING_VANGUARD,
  CARD_ID.SOLITARY_PEAK_SWORDSMAN,
  CARD_ID.SOLITARY_PEAK_SWORDSMAN,
  CARD_ID.SOLITARY_PEAK_SWORDSMAN,
  CARD_ID.FORMATION_CLEARING_MERCENARY,
  CARD_ID.FORMATION_CLEARING_MERCENARY,
  CARD_ID.FORMATION_CLEARING_MERCENARY,
  CARD_ID.CRIMSON_BLADE_INFILTRATOR,
  CARD_ID.CRIMSON_BLADE_INFILTRATOR,
  CARD_ID.CRIMSON_BLADE_INFILTRATOR,
  CARD_ID.BEACON_HEAVY_CAVALRY,
  CARD_ID.BEACON_HEAVY_CAVALRY,
  CARD_ID.LONE_ARMY_GENERAL,
  CARD_ID.LONE_ARMY_GENERAL,
  CARD_ID.ASH_DISMANTLER,
  CARD_ID.ASH_DISMANTLER,
  CARD_ID.EXHAUSTED_VOLCANO_DRAGON,
  CARD_ID.EXHAUSTED_VOLCANO_DRAGON,
  CARD_ID.RETURN_FIRE,
  CARD_ID.FIREBALL_ASSAULT,
  CARD_ID.TIDEWAY_SCOUT,
  CARD_ID.TIDEWAY_SCOUT,
  CARD_ID.TIDEWAY_SCOUT,
  CARD_ID.SPRAY_HERALD,
  CARD_ID.SPRAY_HERALD,
  CARD_ID.MIST_RETURNING_MESSENGER,
  CARD_ID.MIST_RETURNING_MESSENGER,
  CARD_ID.TIDEFRONT_FORTIFIER,
  CARD_ID.TIDEFRONT_FORTIFIER,
  CARD_ID.TIDEFRONT_FORTIFIER,
  CARD_ID.AZURE_WAVE_VOYAGER,
  CARD_ID.AZURE_WAVE_VOYAGER,
  CARD_ID.WAVE_RETURN_MAGE,
  CARD_ID.EPHEMERAL_DEEP_WHALE,
  CARD_ID.LIFE_DROPLET,
] satisfies CardDefinitionId[]

const BLUE_GREEN_INTERCEPT = [
  CARD_ID.TIDEWAY_SCOUT,
  CARD_ID.TIDEWAY_SCOUT,
  CARD_ID.TIDEWAY_SCOUT,
  CARD_ID.SPRAY_HERALD,
  CARD_ID.SPRAY_HERALD,
  CARD_ID.SPRAY_HERALD,
  CARD_ID.SURGING_DUELIST,
  CARD_ID.SURGING_DUELIST,
  CARD_ID.SURGING_DUELIST,
  CARD_ID.MIST_RETURNING_MESSENGER,
  CARD_ID.MIST_RETURNING_MESSENGER,
  CARD_ID.TIDEFRONT_FORTIFIER,
  CARD_ID.TIDEFRONT_FORTIFIER,
  CARD_ID.AZURE_WAVE_VOYAGER,
  CARD_ID.AZURE_WAVE_VOYAGER,
  CARD_ID.AZURE_WAVE_VOYAGER,
  CARD_ID.DEEP_TIDE_INTERCEPTOR,
  CARD_ID.DEEP_TIDE_INTERCEPTOR,
  CARD_ID.DEEP_TIDE_INTERCEPTOR,
  CARD_ID.WAVE_RETURN_MAGE,
  CARD_ID.EPHEMERAL_DEEP_WHALE,
  CARD_ID.EPHEMERAL_DEEP_WHALE,
  CARD_ID.LIFE_DROPLET,
  CARD_ID.TRANSFER,
  CARD_ID.TRANSFER,
  CARD_ID.OAKBARK_SENTINEL,
  CARD_ID.OAKBARK_SENTINEL,
  CARD_ID.OAKBARK_SENTINEL,
  CARD_ID.ROOTED_ANCIENT,
  CARD_ID.VINE_SNARE_HUNTER,
  CARD_ID.VINE_SNARE_HUNTER,
  CARD_ID.GEODE_MINER,
  CARD_ID.GEODE_MINER,
  CARD_ID.ROOT_FORT_REARGUARD,
  CARD_ID.ROOT_FORT_REARGUARD,
  CARD_ID.GREAT_TREE_GUARDIAN,
  CARD_ID.FOREST_CAGE_BEASTMASTER,
  CARD_ID.FOREST_CAGE_BEASTMASTER,
  CARD_ID.DREAMWALKING_FOREST_GIANT,
  CARD_ID.ABUNDANCE,
] satisfies CardDefinitionId[]

const GREEN_RED_FRONTLINE = [
  CARD_ID.OAKBARK_SENTINEL,
  CARD_ID.OAKBARK_SENTINEL,
  CARD_ID.OAKBARK_SENTINEL,
  CARD_ID.ROOTED_ANCIENT,
  CARD_ID.ROOTED_ANCIENT,
  CARD_ID.ROOTED_ANCIENT,
  CARD_ID.VINE_SNARE_HUNTER,
  CARD_ID.VINE_SNARE_HUNTER,
  CARD_ID.VINE_SNARE_HUNTER,
  CARD_ID.GEODE_MINER,
  CARD_ID.GEODE_MINER,
  CARD_ID.ROOT_FORT_REARGUARD,
  CARD_ID.ROOT_FORT_REARGUARD,
  CARD_ID.ROOT_FORT_REARGUARD,
  CARD_ID.GREAT_TREE_GUARDIAN,
  CARD_ID.GREAT_TREE_GUARDIAN,
  CARD_ID.GREAT_TREE_GUARDIAN,
  CARD_ID.FOREST_CAGE_BEASTMASTER,
  CARD_ID.FOREST_CAGE_BEASTMASTER,
  CARD_ID.LEYLINE_MINING_GIANT,
  CARD_ID.LEYLINE_MINING_GIANT,
  CARD_ID.DREAMWALKING_FOREST_GIANT,
  CARD_ID.DREAMWALKING_FOREST_GIANT,
  CARD_ID.DREAMWALKING_FOREST_GIANT,
  CARD_ID.LIFE_CYCLE,
  CARD_ID.SPARK_SWORDSMAN,
  CARD_ID.SPARK_SWORDSMAN,
  CARD_ID.SPARK_SWORDSMAN,
  CARD_ID.BURNING_VANGUARD,
  CARD_ID.FORMATION_CLEARING_MERCENARY,
  CARD_ID.FORMATION_CLEARING_MERCENARY,
  CARD_ID.FORMATION_CLEARING_MERCENARY,
  CARD_ID.CRIMSON_BLADE_INFILTRATOR,
  CARD_ID.CRIMSON_BLADE_INFILTRATOR,
  CARD_ID.BEACON_HEAVY_CAVALRY,
  CARD_ID.BEACON_HEAVY_CAVALRY,
  CARD_ID.ASH_DISMANTLER,
  CARD_ID.EXHAUSTED_VOLCANO_DRAGON,
  CARD_ID.EXHAUSTED_VOLCANO_DRAGON,
  CARD_ID.RETURN_FIRE,
] satisfies CardDefinitionId[]

export const THEME_DECKS = [
  {
    id: 'red-blue-skirmish',
    name: '遊撃突破',
    colors: ['red', 'blue'],
    description: '青の進軍・橋頭堡・帰還で侵入路を作り、赤の単独突破を狙う。',
    cardDefinitionIds: RED_BLUE_SKIRMISH,
  },
  {
    id: 'blue-green-intercept',
    name: '分断迎撃',
    colors: ['blue', 'green'],
    description: '青の位置制御と反撃を、緑の高防御・捕獲・しんがりで支える。',
    cardDefinitionIds: BLUE_GREEN_INTERCEPT,
  },
  {
    id: 'green-red-frontline',
    name: '連環戦線',
    colors: ['green', 'red'],
    description: '緑の採掘拠点を維持し、赤の基礎火力・撤去・刺客で反攻する。',
    cardDefinitionIds: GREEN_RED_FRONTLINE,
  },
] satisfies ThemeDeck[]

export const THEME_DECK_BY_ID = {
  'red-blue-skirmish': THEME_DECKS[0],
  'blue-green-intercept': THEME_DECKS[1],
  'green-red-frontline': THEME_DECKS[2],
} satisfies Record<ThemeDeckId, ThemeDeck>
