import type { CardColor } from './types'

export const THEME_DECK_IDS = [
  'red-blue-skirmish',
  'blue-green-intercept',
  'green-red-frontline',
] as const

export type ThemeDeckId = (typeof THEME_DECK_IDS)[number]

export type ThemeDeck = {
  id: ThemeDeckId
  name: string
  colors: [CardColor, CardColor]
  description: string
  cardDefinitionIds: readonly string[]
}

const RED_BLUE_SKIRMISH = [
  'red-cost2-attack3-defense2-march1',
  'red-cost2-attack3-defense2-march1',
  'red-cost2-attack3-defense2-march1',
  'red-cost2-attack4-defense1-march1',
  'red-cost2-attack4-defense1-march1',
  'red-cost2-attack2-defense1-march1-lone-warrior-2-0',
  'red-cost2-attack2-defense1-march1-lone-warrior-2-0',
  'red-cost2-attack2-defense1-march1-lone-warrior-2-0',
  'red-cost2-attack3-defense1-march1-withdraw',
  'red-cost2-attack3-defense1-march1-withdraw',
  'red-cost2-attack2-defense1-march1-assassin2',
  'red-cost2-attack2-defense1-march1-assassin2',
  'red-cost2-attack2-defense1-march1-assassin2',
  'red-cost4-attack5-defense2-march2',
  'red-cost4-attack5-defense2-march2',
  'red-cost4-attack4-defense2-march2-lone-warrior-2-1',
  'red-cost4-attack4-defense2-march2-lone-warrior-2-1',
  'red-cost4-attack5-defense1-march2-withdraw',
  'red-cost5-attack7-defense4-march2-vanish',
  'red-cost5-attack7-defense4-march2-vanish',
  'cost0-spell-return-fire',
  'cost0-spell-return-fire',
  'blue-cost2-attack2-defense2-march2',
  'blue-cost2-attack2-defense2-march2',
  'blue-cost2-attack2-defense2-march2',
  'blue-cost2-attack2-defense1-march3',
  'blue-cost2-attack2-defense1-march3',
  'blue-cost2-attack3-defense1-march1-counter',
  'blue-cost2-attack3-defense1-march1-counter',
  'blue-cost2-attack2-defense1-march2-return',
  'blue-cost2-attack2-defense1-march2-return',
  'blue-cost2-attack2-defense1-march2-beachhead1',
  'blue-cost2-attack2-defense1-march2-beachhead1',
  'blue-cost2-attack2-defense1-march2-beachhead1',
  'blue-cost4-attack4-defense4-march3',
  'blue-cost4-attack3-defense4-march2-counter',
  'blue-cost4-attack4-defense2-march2-return',
  'blue-cost4-attack4-defense2-march2-return',
  'blue-cost5-attack5-defense6-march4-vanish',
  'cost0-spell-bubble-wall',
] satisfies string[]

const BLUE_GREEN_INTERCEPT = [
  'blue-cost2-attack2-defense2-march2',
  'blue-cost2-attack2-defense2-march2',
  'blue-cost2-attack2-defense2-march2',
  'blue-cost2-attack2-defense1-march3',
  'blue-cost2-attack2-defense1-march3',
  'blue-cost2-attack3-defense1-march1-counter',
  'blue-cost2-attack3-defense1-march1-counter',
  'blue-cost2-attack3-defense1-march1-counter',
  'blue-cost2-attack2-defense1-march2-return',
  'blue-cost2-attack2-defense1-march2-return',
  'blue-cost2-attack2-defense1-march2-beachhead1',
  'blue-cost2-attack2-defense1-march2-beachhead1',
  'blue-cost2-attack2-defense1-march2-beachhead1',
  'blue-cost4-attack4-defense4-march3',
  'blue-cost4-attack4-defense4-march3',
  'blue-cost4-attack3-defense4-march2-counter',
  'blue-cost4-attack3-defense4-march2-counter',
  'blue-cost4-attack4-defense2-march2-return',
  'blue-cost5-attack5-defense6-march4-vanish',
  'blue-cost5-attack5-defense6-march4-vanish',
  'cost0-spell-bubble-wall',
  'cost0-spell-abundance',
  'green-cost2-attack2-defense3-march1',
  'green-cost2-attack2-defense3-march1',
  'green-cost2-attack2-defense3-march1',
  'green-cost2-attack2-defense4-march0',
  'green-cost2-attack2-defense3-march0-capture1',
  'green-cost2-attack2-defense3-march0-capture1',
  'green-cost2-attack2-defense2-march1-mining1',
  'green-cost2-attack2-defense2-march1-mining1',
  'green-cost2-attack2-defense2-march1-rearguard-0-2',
  'green-cost2-attack2-defense2-march1-rearguard-0-2',
  'green-cost2-attack2-defense2-march1-rearguard-0-2',
  'green-cost4-attack4-defense6-march2',
  'green-cost4-attack4-defense5-march1-capture2',
  'green-cost4-attack4-defense5-march1-capture2',
  'green-cost4-attack4-defense4-march2-mining1',
  'green-cost5-attack6-defense7-march2-vanish',
  'green-cost5-attack6-defense7-march2-vanish',
  'cost0-spell-abundance',
] satisfies string[]

const GREEN_RED_FRONTLINE = [
  'green-cost2-attack2-defense3-march1',
  'green-cost2-attack2-defense3-march1',
  'green-cost2-attack2-defense3-march1',
  'green-cost2-attack2-defense4-march0',
  'green-cost2-attack2-defense4-march0',
  'green-cost2-attack2-defense4-march0',
  'green-cost2-attack2-defense3-march0-capture1',
  'green-cost2-attack2-defense3-march0-capture1',
  'green-cost2-attack2-defense2-march1-mining1',
  'green-cost2-attack2-defense2-march1-mining1',
  'green-cost2-attack2-defense2-march1-mining1',
  'green-cost2-attack2-defense2-march1-rearguard-0-2',
  'green-cost2-attack2-defense2-march1-rearguard-0-2',
  'green-cost4-attack4-defense6-march2',
  'green-cost4-attack4-defense6-march2',
  'green-cost4-attack4-defense5-march1-capture2',
  'green-cost4-attack4-defense4-march2-mining1',
  'green-cost4-attack4-defense4-march2-mining1',
  'green-cost5-attack6-defense7-march2-vanish',
  'green-cost5-attack6-defense7-march2-vanish',
  'cost0-spell-abundance',
  'cost0-spell-abundance',
  'red-cost2-attack3-defense2-march1',
  'red-cost2-attack3-defense2-march1',
  'red-cost2-attack3-defense2-march1',
  'red-cost2-attack4-defense1-march1',
  'red-cost2-attack4-defense1-march1',
  'red-cost2-attack2-defense1-march1-lone-warrior-2-0',
  'red-cost2-attack2-defense1-march1-lone-warrior-2-0',
  'red-cost2-attack3-defense1-march1-withdraw',
  'red-cost2-attack3-defense1-march1-withdraw',
  'red-cost2-attack2-defense1-march1-assassin2',
  'red-cost2-attack2-defense1-march1-assassin2',
  'red-cost2-attack2-defense1-march1-assassin2',
  'red-cost4-attack5-defense2-march2',
  'red-cost4-attack5-defense2-march2',
  'red-cost4-attack4-defense2-march2-lone-warrior-2-1',
  'red-cost4-attack5-defense1-march2-withdraw',
  'red-cost5-attack7-defense4-march2-vanish',
  'cost0-spell-return-fire',
] satisfies string[]

export const THEME_DECKS = [
  {
    id: 'red-blue-skirmish',
    name: '遊撃突破',
    colors: ['red', 'blue'],
    description: '青で足場を作り、赤の攻撃力と返り火で突破する。',
    cardDefinitionIds: RED_BLUE_SKIRMISH,
  },
  {
    id: 'blue-green-intercept',
    name: '分断迎撃',
    colors: ['blue', 'green'],
    description: '反撃と高防御を泡の壁で支え、豊穣から戦線を立て直す。',
    cardDefinitionIds: BLUE_GREEN_INTERCEPT,
  },
  {
    id: 'green-red-frontline',
    name: '連環戦線',
    colors: ['green', 'red'],
    description: '緑の拠点と豊穣で戦線を維持し、赤の攻撃力で反攻する。',
    cardDefinitionIds: GREEN_RED_FRONTLINE,
  },
] satisfies ThemeDeck[]

export const THEME_DECK_BY_ID = {
  'red-blue-skirmish': THEME_DECKS[0],
  'blue-green-intercept': THEME_DECKS[1],
  'green-red-frontline': THEME_DECKS[2],
} satisfies Record<ThemeDeckId, ThemeDeck>
